default_job = "check-all"

[jobs.check]
command = ["cargo", "check", "--features", "bevy/dynamic_linking", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--features", "bevy/dynamic_linking", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--features", "bevy/dynamic_linking", "--all-targets", "--color", "always"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.run]
allow_warnings = true
command = ["cargo", "run", "--features", "bevy/dynamic_linking", "--color", "always", "--bin", "client"]
need_stdout = true
