default_job = "check-all"

[jobs.check]
command = ["just", "check"]
need_stdout = false

[jobs.check-all]
command = ["just", "check", "--all-targets"]
need_stdout = false

[jobs.clippy]
command = ["just", "clippy", "--all-targets"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.run]
allow_warnings = true
command = ["just", "client"]
need_stdout = true
