# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "check"

[jobs.check]
command = ["just", "cargo", "check"]
need_stdout = false

[jobs.clippy]
command = ["just", "cargo", "clippy"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.run]
allow_warnings = true
command = ["just", "cargo", "client"]
need_stdout = true
watch = ["examples"]
