[workspace]
members = [
  "crates/engine",
  "crates/client",
  "crates/server",
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.11", default-features = false }
bevy_app = "0.11"
bevy_core = "0.11"
bevy_diagnostic = "0.11"
bevy_ecs = "0.11"
bevy_hierarchy = "0.11"
bevy_log = "0.11"
bevy_math = "0.11"
bevy_reflect = "0.11"
bevy_time = "0.11"
bevy_transform = "0.11"
bevy_utils = "0.11"

# Note on enhanced-determinism:
# If some of the values used to initialized Rapier structures are computed using
# floating points functions (sin, cos, tan, etc.) other than addition/
# subtraction/multiplication/division, then you need to make sure the functions
# being used originate from the ComplexField or RealField traits from nalgebra.
# For example, do ComplexField::sin(0.4) (where ComplexField is imported by use
# nalgebra::ComplexField) instead of 0.4.sin()
# TODO: Change this once a version past 0.22 is out.
# bevy_rapier3d = { version = "0.22", features = ["enhanced-determinism"] }
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", features = ["enhanced-determinism"] }
tracing = "0.1.39"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not our code.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
# Recommended by Rapier for increased performance.
codegen-units = 1
