[package]
edition = "2021"
name = "gam"
version = "0.1.0"

[dependencies]
bevy = { version = "0.10", default-features = false, features = [
  "animation",
  "bevy_asset",
  # "bevy_audio",
  "bevy_gilrs",
  "bevy_scene",
  "bevy_winit",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_gltf",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "png",
  "hdr",
  "ktx2",
  "zstd",
  # "vorbis",
  "x11",
  "filesystem_watcher",
  # "bevy_gizmos",
  "android_shared_stdcxx",
  "tonemapping_luts",
  # "default_font",
  "serialize",
] }
bevy-debug-text-overlay = { version = "5.1.0", optional = true }
bevy_egui = { version = "0.20.3", optional = true }
bevy_hanabi = { version = "0.6.1", default-features = false, features = ["3d"], optional = true }
bevy_kira_audio = { version = "0.15.0", features = ["mp3"] }
bevy_mod_inverse_kinematics = { version = "0.3.0", optional = true }
# bevy_quickmenu = "0.1"
# Note on enhanced-determinism:
# If some of the values used to initialized Rapier structures are computed using
# floating points functions (sin, cos, tan, etc.) other than addition/
# subtraction/multiplication/division, then you need to make sure the functions
# being used originate from the ComplexField or RealField traits from nalgebra.
# For example, do ComplexField::sin(0.4) (where ComplexField is imported by use
# nalgebra::ComplexField) instead of 0.4.sin()
bevy_rapier3d = { version = "0.21", features = ["enhanced-determinism"] }
# bincode = { version = "2.0.0-rc.2", features = ["serde"] }
directories = "5"
glob = "0.3.1"
iyes_progress = { version = "0.8.0", features = ["assets"] }
leafwing-input-manager = { version = "0.9.2" }
nalgebra = "0.32.2"
rand = "0.8"
serde = "1"
serde_json = "1"
smallvec = "1"
thiserror = "1"
# toml = "0.5"
tracing = "0.1"
# tracing-subscriber = "0.3"
# typed-builder = "0.11"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
# Recommended by rapier for increased performance.
codegen-units = 1

[features]
debug = []
default = ["graphics"]
graphics = ["bevy_hanabi", "bevy_egui", "bevy_mod_inverse_kinematics", "bevy-debug-text-overlay"]
