[package]
name = "gam"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9", features = ["serialize"] }
bevy_quickmenu = "0.1"
# Note on enhanced-determinism:
# If some of the values used to initialized Rapier structures are computed using
# floating points functions (sin, cos, tan, etc.) other than addition/
# subtraction/multiplication/division, then you need to make sure the functions
# being used originate from the ComplexField or RealField traits from nalgebra.
# For example, do ComplexField::sin(0.4) (where ComplexField is imported by use
# nalgebra::ComplexField) instead of 0.4.sin()
bevy_rapier2d = { version = "0.19", features = ["enhanced-determinism"] }
big-brain = "0.15.0"
directories = "4"
iyes_loopless = "0.9"
rand = "0.8"
ron = "0.8"
rurel = "0.2"
serde = "1"
serde_json = "1"
thiserror = "1"
# toml = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[features]
default = ["graphics"]
graphics = []

[[bin]]
name = "gam"
required-features = ["graphics"]

[[bin]]
name = "headless"
required-features = []