[workspace]
members = [
  "crates/engine",
  "crates/client",
  "crates/server",
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.16.1", default-features = false }
bevy_rapier3d = { version = "0.31", features = ["enhanced-determinism"] }
smallvec = "2.0.0-alpha.11"
subenum = "1.1.2"
tracing = "0.1.41"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not our code.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
# Recommended by Rapier for increased performance.
codegen-units = 1

[workspace.lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
