[target.x86_64-unknown-linux-gnu]
rustflags = ["-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/home/paho/.xwin/crt/lib/x86_64",
  "-Lnative=/home/paho/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/paho/.xwin/sdk/lib/ucrt/x86_64",
]
