[package]
edition = "2021"
name = "server"
version = "0.1.0"

[dependencies]
# Internal crates
engine.path = "../engine"

# Bevy crates
bevy_app.workspace = true
bevy_ecs.workspace = true
bevy_internal.workspace = true

# Other crates
