on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all-succeeded:
    name: All Succeeded
    if: always()
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
      - name: Check if all jubs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  test:
    name: Test
    runs-on: "${{ matrix.os }}-latest"
    env:
      RUSTFLAGS: -D warnings
    strategy:
      matrix:
        os:
          - windows
          - ubuntu
          - macos
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Bevy Deps
        run: sudo apt-get update && sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - run: cargo fmt --all -- --check
        if: runner.os == 'linux'
      - run: cargo clippy -- -D warnings
        if: runner.os == 'linux'
      - run: cargo test
