on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  all-succeeded:
    name: All Succeeded
    if: always()
    runs-on: ubuntu-latest
    needs:
    - test
    steps:
      - name: Check if all jubs succeeded
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  test:
    name: Test
    runs-on: "${{ matrix.os }}-latest"
    env:
      RUSTFLAGS: -D warnings
    strategy:
      matrix:
        os:
          - windows
          - ubuntu
          - macos
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo test
