on:
  push:
    tags:
      - 'v*'

name: Publish new version

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: windows-latest, target: "x86_64-pc-windows-msvc" }
          - { os: ubuntu-latest, target: "x86_64-unknown-linux-gnu" }
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: git lfs pull
      - uses: Swatinem/rust-cache@v2
      - name: Install Bevy Deps
        run: sudo apt-get update && sudo apt-get install --no-install--recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - name: Build
        run: cargo build --release --locked --target ${{ matrix.config.target }} --bin client
      - name: Prepare
        run: |
          ./github_build.sh ${{ github.ref_name }} ${{ matrix.config.target }}
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ${{ env.TARGET }}
