on:
  push:
    tags:
      - 'v*'

name: Publish new version

defaults:
  run:
    shell: bash

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: windows-latest, target: "x86_64-pc-windows-msvc" }
          - { os: ubuntu-latest, target: "x86_64-unknown-linux-gnu" }
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: git lfs pull
      - uses: dtolnay/rust-toolchain@stable
      # Ugh, Github does not allow jobs of different tags to share a cache, even
      # though they're on the same freaking branch. I am very annoyed.
      # We could probably set-up a job to build the same way on main, and then I
      # think tagged jobs could use that cache. So stupid.
      # Long-term, I think we just build in nix and use cachix or something.
      # See: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
      # - uses: Swatinem/rust-cache@v2
      - name: Install Bevy Deps
        run: sudo apt-get update && sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'
      - name: Build
        run: ./github_build.sh ${{ matrix.config.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: gam-*.zip
  release:
    name: Issue release
    runs-on: ubuntu-latest
    needs: prepare_release
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: "latest"
          files: gam-*.zip
