on:
  push:
    tags:
      - 'v*'

name: Publish new version

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - run: git lfs pull
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Install Bevy Deps
        run: sudo apt-get update && sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Prepare
        run: |
          ./github_build.sh x86_64-pc-windows-msvc x86_64-unknown-linux-gnu
      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          automatic_release_tag: "latest"
          files: |
            gam-*.zip
